### PR TITLE
MRK-16333: Localized footer

### PR DESCRIPTION
**Pull request by adesege**
The home page of 1.1.1.1 is about our WARP client (now) — and it's in the "new design" with links to DNS and Family. The DNS page of 1.1.1.1 is about the public resolver — "old design," with no header links to the new pages. 

This PR adds the 1.1.1.1/Famililies link in the header nav of the old-design. It also adds localization to the footer links and updates the Indonesian locale to indonesia

The goal is that a user, in any language, should be able to navigate between the home page and all the items in the top nav.

# How to test
1. Clone https://github.com/adesege/1.1.1.1 then checkout to my branch mrk-16333-localized-footer.
2. Run yarn install to install dependencies then run yarn build to build the project for production
3. Visit Cloudflare Pages and select one-dot-one then create a new deployment. In the following page that opens, choose upload a folder and select the build directory from the root of the cloned project. Then click save.

# Preview
https://one-dot-one.pages.dev

### CODE REVIEW

**Comment by tsmith512** [comment]
For point 2, "Indonesia" is the name of that language in the language, or so it has been explained to me. David Fidalgo has some context.

For 1, do we want to remove what is essentially the "home" page link from the nav just on the home page? Remembering that the CF logo points off-site to www

**Comment by mgalicer** [comment]
yep, just on homepage. on old site if you navigate to 1.1.1.1/ it looks like this, which makes sense to me (not to have the redundancy)
Screenshot 2023-03-28 at 1 57 50 PM

**Comment by adesege** [comment]
Thanks for your feedback @mgalicer. For 3, is this okay?
Screenshot 2023-03-28 at 7 14 01 PM

**Comment by mgalicer** [comment]
lgtm!

**Pull request merged**
